class AmazonPrime{

 static String kannadaMovies[]={"Rakta kanniru","Upendra","Auto Shankar","Gokarna","Gowtramma","Uppidada MBBS","Nagarahavu","Nanu nane","Kutumba","Hollywood","Dange danger","Kannamuchchaale","News","H2O","Omkara","Preethse","Mast majaa maadi","Prema prema"," Gelathiye","Shakalaka bhoom","Superstar","Chakkar haku","Kalpana","Na ninna bidalaare","Rasika"};
 static String hindiMovies[]={"Ghajini","3 idiots","Dabang","Golmal","Ready","Singham","Bodyguard","Don2","Agneepath","Housefull2","Rowdy Rathore","Bol Bachchan","Ek tha tiger","Barfi","Son of sardaar","Jab tak hai jaan","Dhoom","Dil bechara","Krish","Sanam teri kasam","Pathan","BhoolBhulaiyaa","Dhamaka","Bhajarangi Bahijan","Gangubai"};
 static String teluguMovies[]={"Veer zaara","C/o kancharapalem","Mayabazar","Jersey","Sita ramam","Nuvu Naaku nachchav","Aha naa pellanta","Mahanati","Agent sai srinivasa athreya","Aa Naluguru","Bahubali2","Bommarillu","Sankarabharanam","Rangasthalam","Athadu","Pelli choopu;u","Manmadhudhu","Kshanam","Mathu vadalara","Evaru","Drushyam","Aditya","Vedam","Gamyam","Prasthanam"};
 static String englishMovies[]={"The shawshank redemption","The Godfather","The dark knight","The Godfather part2","12 andry men","Schindler list","The lord of rings","Spiderman","Pulp Fiction","Forrest Gump","Fight club","Inception","Star wars","The matrix","Goodfellas","Its wonderful life","Se7ven","Interstellar","The silence of the lambs","Saving Private ryan","The green mile","Terminator2","Back to the future","The Pianist","Psyco"};
 static String malayalamMovies[]={"Drishyam","Kaalapani","Ustad hotel","The ornate lock","Kilukkam","Devasuram","Pranchiyettan","Unda","The great indian kitchen","Iratta","Oru kuprasidha payyan","Adaminte makan abu","Aathmakatha","Munnariyippu","Eemayau","Baahubali","Romancham","Jo and jo","Jallikattu","Kumbalangi nights","Premam","Indian rupee","Thanmathra","Bangalore days","The address"};
 
 
     public static void main(String prime[]){
	 System.out.println(kannadaMovies[0] +" "+ kannadaMovies[1] +" "+ kannadaMovies[2] +" "+ kannadaMovies[3] +" "+ kannadaMovies[4] +" "+ kannadaMovies[5] +" "+ kannadaMovies[6] +" "+ kannadaMovies[7] +" "+ kannadaMovies[8] +" "+ kannadaMovies[9] +" "+ kannadaMovies[10] +" "+ kannadaMovies[11] +" "+ kannadaMovies[12] +" "+ kannadaMovies[3] +" "+ kannadaMovies[14] +" "+ kannadaMovies[15] +" "+ kannadaMovies[16] +" "+ kannadaMovies[17] +" "+ kannadaMovies[18] +" "+ kannadaMovies[19] +" "+ kannadaMovies[20] +" "+ kannadaMovies[21] +" "+ kannadaMovies[22] +" "+ kannadaMovies[23] +" "+ kannadaMovies[24] );
	 System.out.println(hindiMovies[0] +" "+ hindiMovies[1] +" "+ hindiMovies[2] +" "+ hindiMovies[3] +" "+ hindiMovies[4] +" "+ hindiMovies[5] +" "+ hindiMovies[6] +" "+ hindiMovies[7] +" "+ hindiMovies[8] +" "+ hindiMovies[9] +" "+ hindiMovies[10] +" "+ hindiMovies[11] +" "+ hindiMovies[12] +" "+ hindiMovies[13] +" "+ hindiMovies[14] +" "+ hindiMovies[15] +" "+ hindiMovies[16] +" "+ hindiMovies[17] +" "+ hindiMovies[18] +" "+ hindiMovies[19] +" "+ hindiMovies[20] +" "+ hindiMovies[21] +" "+ hindiMovies[22] +" "+ hindiMovies[23] +" "+ hindiMovies[24] );
	 System.out.println(teluguMovies[0] +" "+ teluguMovies[1] +" "+ teluguMovies[2] +" "+ teluguMovies[3] +" "+ teluguMovies[4] +" "+ teluguMovies[5] +" "+ teluguMovies[6] +" "+ teluguMovies[7] +" "+ teluguMovies[8] +" "+ teluguMovies[9] +" "+ teluguMovies[10] +" "+ teluguMovies[11] +" "+ teluguMovies[12] +" "+ teluguMovies[13] +" "+ teluguMovies[14] +" "+ teluguMovies[15] +" "+ teluguMovies[16] +" "+ teluguMovies[17] +" "+ teluguMovies[18] +" "+ teluguMovies[19] +" "+ teluguMovies[20] +" "+ teluguMovies[21] +" "+ teluguMovies[22] +" "+ teluguMovies[23] +" "+ teluguMovies[24]);
	 System.out.println(englishMovies[0] +" "+ englishMovies[1] +" "+ englishMovies[2] +" "+ englishMovies[3] +" "+ englishMovies[4] +" "+ englishMovies[5] +" "+ englishMovies[6] +" "+ englishMovies[7] +" "+ englishMovies[8] +" "+ englishMovies[9] +" "+ englishMovies[10] +" "+ englishMovies[11] +" "+ englishMovies[12] +" "+ englishMovies[13] +" "+ englishMovies[14] +" "+ englishMovies[15] +" "+ englishMovies[16] +" "+ englishMovies[17] +" "+ englishMovies[18] +" "+ englishMovies[19] +" "+ englishMovies[20] +" "+ englishMovies[21] +" "+ englishMovies[22] +" "+ englishMovies[23] +" "+ englishMovies[24] );
	 System.out.println(malayalamMovies[0] +" "+ malayalamMovies[1] +" "+ malayalamMovies[2] +" "+ malayalamMovies[3] +" "+ malayalamMovies[4] +" "+ malayalamMovies[5] +" "+ malayalamMovies[6] +" "+ malayalamMovies[7] +" "+ malayalamMovies[8] +" "+ malayalamMovies[9] +" "+ malayalamMovies[10] +" "+ malayalamMovies[11] +" "+ malayalamMovies[12] +" "+ malayalamMovies[13] +" "+ malayalamMovies[14] +" "+ malayalamMovies[15] +" "+ malayalamMovies[16] +" "+ malayalamMovies[17] +" "+ malayalamMovies[18] +" "+ malayalamMovies[19] +" "+ malayalamMovies[20] +" "+ malayalamMovies[21] +" "+ malayalamMovies[22] +" "+ malayalamMovies[23] +" "+ malayalamMovies[24] );
	 }
}